targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
          - --minify
          - --fast-startup
          - -DPRE_NULL_SAFETY_SERVER_URL=https://v1.api.dartpad.dev/
          - -DNULL_SAFETY_SERVER_URL=https://nullsafety.api.dartpad.dev/